# Generated by Django 2.2.1 on 2019-08-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googleform', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='name',
            name='username',
        ),
        migrations.AddField(
            model_name='name',
            name='姓名',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='name',
            name='手機號碼',
            field=models.IntegerField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
