# Generated by Django 2.2.1 on 2019-08-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googleform', '0002_auto_20190810_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='手機號碼',
            field=models.CharField(max_length=10),
        ),
    ]
