# Generated by Django 2.2.1 on 2019-08-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googleform', '0003_auto_20190810_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='我想說的話',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
    ]
