# Generated by Django 2.2.1 on 2019-08-11 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('googleform', '0004_name_我想說的話'),
    ]

    operations = [
        migrations.RenameField(
            model_name='name',
            old_name='我想說的話',
            new_name='我想兌換的東西',
        ),
    ]
