# Generated by Django 2.2.1 on 2019-08-12 12:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('googleform', '0005_auto_20190811_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
