# Generated by Django 2.2.1 on 2019-08-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googleform', '0006_name_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='我要幾台iphone',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
    ]
