# Generated by Django 2.2.1 on 2019-08-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googleform', '0008_auto_20190812_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='我要幾台iphone',
            field=models.IntegerField(choices=[('5張發票', '1'), ('10張發票', '2'), ('3', '3'), ('4', '4'), ('5', '5')]),
        ),
    ]
