# Generated by Django 2.2.1 on 2019-08-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googleform', '0010_auto_20190812_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='我要幾台iphone',
            field=models.CharField(choices=[('1', '1(5張發票)'), ('2', '2(10張發票)'), ('3', '3(30張發票)'), ('4', '4(40張發票)'), ('5', '5(50張發票)')], max_length=10),
        ),
    ]
